name: Supabase Migrations

on:
  push:
    branches:
      - main
    paths:
      - 'supabase/migrations/**'

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Supabase CLI
        run: |
          curl -fsSL https://github.com/supabase/cli/releases/download/v1.145.0/supabase_1.145.0_linux_amd64.tar.gz | tar xz
          sudo mv supabase /usr/local/bin/
      
      - name: Show Supabase version
        run: supabase --version
      
      - name: Login to Supabase
        run: supabase login --token ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      
      - name: Link to project
        run: |
          echo "Project Ref: ${{ secrets.SUPABASE_PROJECT_REF }}"
          supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
      
      - name: List migrations
        run: supabase migration list
      
      - name: Push migrations
        run: supabase db push
        continue-on-error: false
      
      - name: Show migration status
        run: supabase migration status 